version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw test
  post_build:
    commands:
      - echo Build completed on `date`
