name: Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  dependency_submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v4.0.2
