name: Native Image CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  find-submodules:
    name: Find submodules
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          SUBMODULES=$(./mvnw -Dexec.executable='echo' -Dexec.args='${project.artifactId}' exec:exec -q | jq -Rn '[inputs]' --compact-output)
          echo $SUBMODULES
          echo "matrix={\"maven_submodules\":$SUBMODULES}" >> $GITHUB_OUTPUT
  build:
    needs: [find-submodules]
    strategy:
      fail-fast: false
      matrix:
        matrix: ${{ fromJson(needs.find-submodules.outputs.matrix) }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
      - name: Build with Maven
        run: ./mvnw -pl ${{matrix.maven_submodules}} test -PnativeTest
